[package]
name = "wasm_guest"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }
dioxus-core = { version = "0.6.3", default-features = false }
dioxus-core-macro = "0.6.2"
dioxus-signals = { version = "0.6.2", default-features = false }
dioxus-hooks = { version = "0.6.2", default-features = false }
dioxus-html = { version = "0.6.2", default-features = false }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:wasm-guest"

[package.metadata.component.dependencies]